services:
  backend:
    volumes:
      - ./backend:/app/backend
    depends_on:
      - redis

  worker:
    image: meeting-notes-assistant-backend   # reuse backend image
    command: python -m worker.worker         # run RQ worker
    volumes:
      - ./backend:/app/backend
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
