"""add jobs table (clean)

Revision ID: 2b490b6836b2
Revises: 35504527d3de
Create Date: 2025-09-23 18:49:22.781784

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '2b490b6836b2'
down_revision: str | Sequence[str] | None = '35504527d3de'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
