"""add jobs table

Revision ID: 35504527d3de
Revises: 25a89a297432
Create Date: 2025-09-23 18:42:09.924853

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '35504527d3de'
down_revision: str | Sequence[str] | None = '25a89a297432'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
